name: git_hooks
description: Using dart to prevents bad commit or push (git hooks, pre-commit/precommit, pre-push/prepush, post-merge/postmerge and all that stuff...).It is similar to husky.
version: 0.1.3-nullsafety.0
homepage: https://github.com/xuzhongpeng/git_hooks

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  path: ^1.8.0
  yaml: ^3.1.0

dev_dependencies:
  test: ^1.17.12
  lint: ^1.8.2
executables:
  git_hooks:
